#!/bin/bash

source /etc/update-motd.d/colors.txt

load_average=$(cat /proc/loadavg)

echo -e " ${YEL}Load Averages.......:${NC} 1 min: ${PUR}$($load_average | cut -f1 -d' ')${NC} 5 mins: ${PUR}$($load_average | cut -f2 -d' ')${NC} 15 mins: ${PUR}$($load_average | cut -f3 -d' ')${NC}"
