#!/bin/bash

source /etc/update-motd.d/colors.txt
source /etc/update-motd.d/config.conf

QUEUE="$(curl -s "$SABHOST:$SABPORT/sabnzbd/api?mode=qstatus&apikey=$SABAPI&output=json")"

echo -e " ${YEL}SABNZBD Queue.......:${NC} There are currently ${PUR}$(echo "$QUEUE" | jq ".value.noofslots_total")${NC} slots in queue"
echo -e " ${YEL}SABNZBD Speed.......:${NC} Currently downloading at ${PUR}$(echo "$QUEUE" | jq ".value.kbpersec" | tr -d '"')${NC} KB/s"
echo -e " ${YEL}Remaining...........:${NC} ${PUR}$(echo "$QUEUE" | jq ".value.mb" | tr -d '"')${NC} MB"
