#!/bin/bash

YEL='\033[0;33m'
PUR='\033[0;35m'
NC='\033[0m'

echo -e " ${YEL}Torrents............:${NC} There are currently ${PUR}$(transmission-remote -n 'username:password' -l | wc -l)${NC} torrents in Transmission"
echo -e " ${YEL}Seeding Torrents....:${NC} There are currently ${PUR}$(transmission-remote -n 'username:password' -l | grep Seeding | wc -l)${NC} torrents actively seeding"
echo -e " ${YEL}Downloaded..........:${NC} ${PUR}$(transmission-remote -n 'username:password' -st | tail -5 | grep Uploaded | cut -f2 -d':' | xargs)${NC}"
echo -e " ${YEL}Uploaded............:${NC} ${PUR}$(transmission-remote -n 'username:password' -st | tail -5 | grep Downloaded | cut -f2 -d':' | xargs)${NC}"
echo -e " ${YEL}Ratio...............:${NC} ${PUR}$(transmission-remote -n 'username:password' -st | tail -5 | grep Ratio | cut -f2 -d':' | xargs)${NC}"
