#!/bin/bash

MY_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${MY_PATH}/colors.txt"
source "${MY_PATH}/config.conf"

if ! [ -e /usr/bin/transmission-remote ]; then
        exit 1
fi

LIST="$(/usr/bin/transmission-remote $TRANSIP:$TRANSPORT -n $TRANSUSER:$TRANSPASS -l)"
STATS="$(/usr/bin/transmission-remote $TRANSIP:$TRANSPORT -n $TRANSUSER:$TRANSPASS -st | tail -5)"

echo $LIST

echo -e " ${YEL}Torrents............:${NC} There are currently ${PUR}$(echo "$(echo "$LIST" | wc -l) - 2" | bc)${NC} torrents in Transmission"
echo -e " ${YEL}Seeding Torrents....:${NC} There are currently ${PUR}$(echo "$LIST" | grep Seeding | wc -l)${NC} torrents actively seeding"
echo -e " ${YEL}Downloaded..........:${NC} ${PUR}$(echo "$STATS" | grep Downloaded | cut -f2 -d':' | xargs)${NC}"
echo -e " ${YEL}Uploaded............:${NC} ${PUR}$(echo "$STATS" | grep Uploaded | cut -f2 -d':' | xargs)${NC}"
echo -e " ${YEL}Ratio...............:${NC} ${PUR}$(echo "$STATS" | grep Ratio | cut -f2 -d':' | xargs)${NC}"
