#!/bin/bash

MY_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${MY_PATH}/colors.txt"
source "${MY_PATH}/config.conf"

# Check for services file from config.conf.
if [ -f "${SERVICEFILE}" ]; then
	readarray -t SERVICES < "${SERVICEFILE}"
# Check to see if we have a service file in the directory where the script is run.
elif [ -f "${MY_PATH}/services" ]; then
	readarray -t SERVICES < "${MY_PATH}/services"
# We don't have a service file, lets default to just checking for plex.
else
	SERVICES=(
		"plexmediaserver"
	)
fi

service_check(){
	STATE=$(service $1 status | grep "active (running)" | wc -l)
		if [ "$STATE" = "1" ]; then
			echo -e "${GRN}OK!${NC}"
		else
			echo -e "${RED}Not running...${NC}"
		fi
}

pad=$(printf "%0.1s" "${PAD_CHARACTER}"{1..60})

for index in "${!SERVICES[@]}"; do
	printf " ${YEL}%s " "${SERVICES[index]}"
	SERVICE_LENGTH=${#SERVICES[index]}
	STATE=$(service_check "${SERVICES[index]}")
	STATE_LENGTH=${#STATE}
	printf "%*.*s${NC} ${STATE}\n" 0 $((PAD_LENGTH - SERVICE_LENGTH - STATE_LENGTH)) "$pad"
done
