#!/bin/bash

source /etc/update-motd.d/colors.txt

service_check(){

STATE=$(service $1 status | grep "active (running)" | wc -l)
	if [ "$STATE" = "1" ]; then
		echo -e "${GRN}OK!${NC}"
	else
		echo -e "${RED}Not running...${NC}"
	fi
}

PLEXSTATE=$(service_check plexmediaserver)
TRANSSTATE=$(service_check transmission-daemon)
TAUTSTATE=$(service_check tautulli)
OMBISTATE=$(service_check ombi)

echo -e " ${YEL}Plex Status.........:${NC} $(echo $PLEXSTATE)"
echo -e " ${YEL}Transmission Status.:${NC} $(echo $TRANSSTATE)"
echo -e " ${YEL}Tautulli Satus......:${NC} $(echo $TAUTSTATE)"
echo -e " ${YEL}Ombi Status.........:${NC} $(echo $OMBISTATE)"
