#!/bin/bash

source /etc/update-motd.d/config.conf
source /etc/update-motd.d/colors.txt
/bin/bash /etc/update-motd.d/dependency-check.sh

echo -e " ${YEL}Missing Movies .....:${NC} There are currently ${PUR}$(curl -s $RADARRHOST:$RADARRPORT/api/wanted/missing?apikey=$RADARRAPI |jq -r '.totalRecords')${NC} Movies  missing in Radarr"
